# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlQuery


class Ui_AddClient(object):
    def setupUi(self, AddClient):
        AddClient.setObjectName("AddClient")
        AddClient.resize(335, 413)
        AddClient.setStyleSheet("background-color: rgb(188, 235, 255)")
        self.centralwidget = QtWidgets.QWidget(AddClient)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 141, 20))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 80, 141, 20))
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 120, 141, 20))
        self.lineEdit_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 160, 141, 20))
        self.lineEdit_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 200, 141, 20))
        self.lineEdit_5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(130, 240, 141, 22))
        self.dateEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 320, 141, 22))
        self.comboBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 280, 141, 20))
        self.lineEdit_7.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 360, 75, 23))
        self.pushButton.setStyleSheet("background-color:rgb(208, 219, 255)")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 320, 47, 13))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 360, 75, 23))
        self.pushButton_2.setStyleSheet("background-color:rgb(208, 219, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        AddClient.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddClient)
        QtCore.QMetaObject.connectSlotsByName(AddClient)

    def retranslateUi(self, AddClient):
        _translate = QtCore.QCoreApplication.translate
        AddClient.setWindowTitle(_translate("AddClient", "Добавить нового клиента"))
        self.pushButton.setText(_translate("AddClient", "Сохранить"))
        self.label.setText(_translate("AddClient", "Фамилия"))
        self.label_2.setText(_translate("AddClient", "Имя"))
        self.label_3.setText(_translate("AddClient", "Отчество"))
        self.label_4.setText(_translate("AddClient", "Почта"))
        self.label_5.setText(_translate("AddClient", "Телефон"))
        self.label_6.setText(_translate("AddClient", "День рождения"))
        self.label_7.setText(_translate("AddClient", "Фото"))
        self.label_8.setText(_translate("AddClient", "Пол"))
        self.pushButton_2.setText(_translate("AddClient", "Отмена"))
        self.displayData()

    def displayData(sqlStatment, db):
        db.open()
        print("Загрузка приложения ...")
        query = QSqlQuery(db)
        query.prepare(sqlStatment)
        query.exec()
        list = []
        while query.next():
            FirstName = query.value(0)
            clie = QSqlQuery(db)
            clie.prepare("select * from Client where LastName='" + FirstName + "'");
            clie.exec()
            clien = ""
            while clie.next():
                firstN = sup.value(1)
                clien += firstN + ", "
            FirstName = query.value(1)
            LastName = query.value(2)
            Patronymic = query.value(3)
            Birthday = int(query.value(5))
            RegistrationDate = int(query.value(9))
            Email = query.value(7)
            Phone = query.value(6)
            GenderCode = query.value(4)
            PhotoPath = query.value(8)
            list.append(
                ClientListZero(FirstName, LastName, Patronymic, Birthday, RegistrationDate, Email, Phone, GenderCode,
                               PhotoPath))
        db.close()
        return list
