# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllClientVisit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowAllVisitClient(object):
    def setupUi(self, WindowAllVisitClient):
        WindowAllVisitClient.setObjectName("WindowAllVisitClient")
        WindowAllVisitClient.resize(328, 214)
        self.centralwidget = QtWidgets.QWidget(WindowAllVisitClient)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 141, 41))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(150, 30, 41, 41))
        self.toolButton.setObjectName("toolButton")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 70, 141, 41))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(150, 70, 41, 41))
        self.toolButton_2.setObjectName("toolButton_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(150, 110, 41, 41))
        self.toolButton_3.setObjectName("toolButton_3")
        WindowAllVisitClient.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WindowAllVisitClient)
        self.statusbar.setObjectName("statusbar")
        WindowAllVisitClient.setStatusBar(self.statusbar)

        self.retranslateUi(WindowAllVisitClient)
        QtCore.QMetaObject.connectSlotsByName(WindowAllVisitClient)

    def retranslateUi(self, WindowAllVisitClient):
        _translate = QtCore.QCoreApplication.translate
        WindowAllVisitClient.setWindowTitle(_translate("WindowAllVisitClient", "Все посещения клиентов"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("WindowAllVisitClient", "Наименование услуги"))
        item = self.listWidget.item(1)
        item.setText(_translate("WindowAllVisitClient", "гггг.мм.дд чч:мм"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.toolButton.setText(_translate("WindowAllVisitClient", "►"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("WindowAllVisitClient", "Наименование услуги"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("WindowAllVisitClient", "гггг.мм.дд чч:мм"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.toolButton_2.setText(_translate("WindowAllVisitClient", "►"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("WindowAllVisitClient", "Наименование услуги"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("WindowAllVisitClient", "гггг.мм.дд чч:мм"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.toolButton_3.setText(_translate("WindowAllVisitClient", "►"))



